services:
  web:
    build:
      context: ../..
      dockerfile: Dockerfile.web
      args:
        VITE_SERVER_URL: ${VITE_SERVER_URL}
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NITRO_PORT=${PORT}
      - VITE_SERVER_URL=${VITE_SERVER_URL}
